Stage 1
WG-Forge/Pigs-on-the-moon pull request #3
Opened 2022-01-31 08:52 UTC by denisprohorov

Our bot can create new game, join game with bot "friends" and play game. Bot also brings the game to an end.

2022-01-31 20:47 UTC, BrychDaneel approved these changes

2022-01-31 20:47 UTC, BrychDaneel commented on modules/gameClient.cpp
> +    return true;
Только на одного игрока рассчитанно пока?

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/game.h
> +using namespace std;
Такое в хидерах как минимум лучше не использовать. Теряется весь смысл нэймспэйсов в с++.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/gameClient.h
> +    bool initGame(const std::string& name, const std::string& password = "",
Кодстиль не выдержен. Иногда название метода с маленькой будквы, иногда с большой.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/gameClient.cpp
> +        game->UpdateAttackMatrix(stoi(pm.key()), v_attacked);
Лишнее копирование вектора.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/game.h
> +    void InitMap(int size);
Ну вообще желательно всю инициализацию из конструкторов делать (по крайней мере опрделяющих полей). В с++ конструктор для этого и предназначен.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/actionController.h
> +    static std::tuple<int, int, int> getTargetForMove(std::tuple<int, int, int> coordinates, Map *map);
Можно сделать type alias, чтобы каждый раз не писать std::tuple<int, int, int>

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/actionController.cpp
> +        return std::make_tuple(-1,-1,-1); // нам не нужно перемещаться, мы на базе
В коментариях лучше придерживаться английского)

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/actionController.cpp
> +        ModuleDecrement(n);
Возможно я ошибаюсь. но кажется что это можно было бы решить эффективнее чем фориком.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/constructions/construction.cpp
> +Construction::~Construction() {
Можно = default;

2022-01-31 20:47 UTC, BrychDaneel commented on modules/map/map.cpp
> +    content.push_back(new Base(basis));
В этой строке одновременно лишнее копирование и утечка памяти.
Я бы рекомендовал бы вам прогнать приложене через valgrind, или через другой отладчик утечек памяти.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/client/client.cpp
> +    std::unique_ptr<char[]> buffer(new char[4 * 2 + msg.size()]);
Можно проще - через std::vector

2022-01-31 20:47 UTC, BrychDaneel commented on main.cpp
> +            gc.initGame("test14", "", game, numbersTurn, numbersCount);
В этом кейсе вместо std::string& хороше подошёл бы std::string_view. С ним на одно копирование меньше будет.

2022-01-31 20:47 UTC, BrychDaneel commented on modules/game/game.cpp
> +    player = new Player(id, name, password);
Лишнее копирование name

2022-01-31 20:47 UTC, BrychDaneel commented on modules/actors/player.cpp
> +    this->password = pass;
Лишнее копирование

2022-01-31 20:47 UTC, BrychDaneel commented on modules/actors/vehicle.cpp
> +int Vehicle::Shoot(Vehicle *v) { // вернет сколько очков заработал
Если входной аргумент не может быть nullptr, то лучше использовать ссылку вместо указателя.

2022-02-01 12:09 UTC, ZhekLu commented on modules/game/game.h
> +using namespace std;
> Такое в хидерах как минимум лучше не использовать. Теряется весь смысл нэймспэйсов в с++.

Вы имеете в виду std или енамы, которые дефайнят свои имена? Когда много кода с std, говорили std подключать это не так плохо, просто в cpp перенести?

2022-02-01 12:13 UTC, ZhekLu commented on modules/game/game.h
> +    void InitMap(int size);
> Ну вообще желательно всю инициализацию из конструкторов делать (по крайней мере опрделяющих полей). В с++ конструктор для этого и предназначен.

Тут фишка в том, что размер мапы узнается только после первого запроса. Я в принципе могу вызвать его прямо в конструкторе. С точки зрения логики программы, так будет правильней? Получается создаем объект GameClient и он при создании делает запрос на сервак.

2022-02-02 12:30 UTC, BrychDaneel commented on modules/map/map.cpp
> +    content.push_back(new Base(basis));
Действитено копирования нет, извиняюсь. Не заметил эмперсанта, непривычный для меня кодстиль. Ну и вцелом пример передачи аргумента в конструктор с целью его мутации не очень типичный.

2022-02-02 12:33 UTC, BrychDaneel commented on modules/map/map.cpp
> +    content.push_back(new Base(basis));
Утечки это грубая ошибка в с++ коде, рекомендовал бы с ними разобраться в первую очередь. И как я уже упоминал, лучше вместо new/delete использовать умные указатели.

2022-02-02 13:13 UTC, BrychDaneel commented on modules/game/game.h
> +using namespace std;
Именно using namespace std;

`говорили std подключать это не так плохо`
Ну, возможно отчасти это дело субъективное конечно. Но зависит еще где вам такое говорили)

Во всех нормальных проектах с++ очень много кода с std. Проблема using namespace std в том что в std нэймпэйсе много идентификатров с общими названиями, типо list, map, vector, move sort и т.п., и если их импортировать в глобальный нэймпэйс, то их могут подхватить в совершенно неожиданных местах. 

Воображаемый пример: допустим в nlohman::json был реализован какой-то свой мега-крутой nlohman::sort. Вы импортируете свой хидер внутри котрого using namespace, а затем хидер nlohman. И теперь в хидере nlohman может быть использован sort из std, потомучто внутри нэймпсэйса nlohman точно не будут явно указывать nlohman::sort. А при наличии двух вариантов sort, далеко не всегда очевидно какой выберет компилятор. Таким образом using namespace в вашем коде может сломать библиотеку, которую вы используете.
В cpp файлах такая проблема не может произойти, если у вас using namespace сторго после инклудов.

Плюс с каждой новой версией в std появляются новые символы. Внезапно, например, там может появится класс Hex. И тогда произойдёт кофнликт с вашим классом Hex, и код не скомпилится.

Ну вообщем есть явлные минусы, которые почти наверняка проявляются в больших проектов, где много сердпатей. В маленьких это не столь актуально, там можно всё проконтролировать и они недолго живут. На эту тему вообще много холивара, если поищете, возможно найдёте более четкие аргументы за или против.

2022-02-02 13:39 UTC, BrychDaneel commented on modules/game/game.h
> +    void InitMap(int size);
Ну да, не всегда такие кейсы лёкго разруливаются. Дело творческое. Но есть смысл пробовать, т.к. с++ целеком на RAII идеоме основан. 
Иногда можно в конструкторе делать сложные вещи, иногда стоит отложить вызов констра, иногда можно создавать переменные в рамках метода, а не как член класса. А может просто если назвать функцию как login, или fetchMap, то у неё уже более валидное решение.

Вообщем это всегда архитектурная задачка. У неё есть вполне конкретная практическая цель: уменьшить ивариантность сущностей и как следствие уменьшить саму возможно писать код неправильно. 
Если на примере: initGame добавляют дополнительное ограничение на класс, что внешний код должен вначале нужно вызвать initGame, потом уже SendAction и т.п. Соотвественно появляется возможность ошибки: внешний код может забыть вызвать initGame и поизодёт краш. Не всегда похожие архитектурные проблемы можно побороть, иногда просто assert вкатывают, но вцелом чем меньше к объектам конвенциональных требований, тем лучше.

2022-02-06 09:24 UTC, ZhekLu requested changes
Some qq.

2022-02-06 09:24 UTC, ZhekLu commented on modules/gameClient.cpp
> +}
И подумал насчет переноса инитов в конструктор GameClient. Но тут проблема. Если сервер откажет в логине, то в конструкторе надо бросить какой-то эксепшн или еще что-то. Это проблемно.
Или не переносить и ставить везде ассерты. И вот вопрос. Лучше оставить все так или практичнее будет поставить ассерты во всех остальных методах? Ну и здесь, чтобы не вызвали дважды. Ассерт это по сути всего-то одна операция. Но они будут вызываться при каждом запросе гейм стейта и отправке запросов в игру. Это не будет костыльно?

2022-02-06 09:24 UTC, ZhekLu commented on modules/gameClient.cpp
> +                                 MakePosTuple(point));
Еще здесь нужен ваш совет. У нас разделились мнения на два лагеря.
Сейчас класс GameClient несет ответственность за коннект client и самой игры game, и собственно за предоставление обоим информации в нужном для них формате. То есть парсит инфу с клиента из json в нужные типы и отправляет игре. 
Первое мнение: Игра не должна знать о том, какой формат информации содержится на сервере, и изменения на сервере должны приводить к изменениям только в одном классе - GameClient. Так игра остается универсальной единицей и играть в нее могут все без привязки к входным данным, которые являются заботой GameClient на уровне выше. 
Второе: Парсинг в GameClient это смещение ответственности, нарушение принципа SOLID. Внутренние классы сами должны парситься с json, а GameClient должен служить как проходной пункт. Получил из клиента json - отправил его в игру, она сама разберется.

2022-02-07 11:18 UTC, seillich approved these changes

2022-02-07 11:18 UTC, seillich commented on modules/gameClient.cpp
> +}
Можно сделать отдельный метод create_connection или что-то в этом духе, где будет происходить логин.

дальше мое видение насчет game:
* Инициализируем в конструкторе, передаем туда map и state например
* Методы addvehicle и тд, точно должны быть привантными, это не зона ответсвенности GameClient
* У game есть метод update_state, куда вы передаете state и больше ничего не должны делать в GameClient, все остальные проблемы -- это проблемы Game

2022-02-07 11:18 UTC, seillich commented on main.cpp
> +    while (!gc.SendTurn()) {}// wait all players
Если совсем по красивому делать, унести это все GameClient, назвать метод старт и просто тут вызывать, зачем в main "условная" логика

2022-02-07 11:18 UTC, seillich commented on modules/gameClient.cpp
> +                                 MakePosTuple(point));
https://github.com/WG-Forge/Pigs-on-the-moon/pull/3#discussion_r800545997

2022-02-08 14:18 UTC, BrychDaneel commented on modules/gameClient.cpp
> +                                 MakePosTuple(point));
>  Внутренние классы сами должны парситься с json, а GameClient должен служить как проходной пункт.

Парсинг данных - это в идеале задача connection model. Завтра например может произойти измение формата на yaml, или на бинарные данные. В хорошей архитектуре логика сущностей AI не поменяется, поменяется только часть которая за коммуникацию отвечает. Как описанно в первом мнении.

> Парсинг в GameClient это смещение ответственности, нарушение принципа SOLID.

Если речь о Single Responsibility, то это тоже справедливо. Но AI тоже не должно заниматься парсингом. Задача AI - играть.

Поэтому с точке зрения этого принципа тут скорее напрашивается новая сущность, которая будет заниматся сериализаций/десериализауий. 
У вас есть Client, которые может отправлять голые данные. Тогда возможно стоит добавить дополнительный слой абтракции, типо ProtocolClient (над название подумайте),  который композирует tpc клиент, и дополнительно парсит json в структуры данные которыми вы оперируете.

2022-02-08 14:36 UTC, BrychDaneel commented on modules/gameClient.cpp
> +                                 MakePosTuple(point));
> который композирует tpc клиент

Ну или не через композицию, а сбоку. Уже разные варианты возможны.

2022-02-08 18:16 UTC, BrychDaneel approved these changes

2022-02-08 18:16 UTC, BrychDaneel commented on modules/actors/player.h
> +    const std::string NAME;
Почему большими буквами?)
За кодстилем надо следить

2022-02-08 18:16 UTC, BrychDaneel commented on modules/map/hex.h
> +    static std::vector<Point> GetRing(Point center, int r);
На такие функции кстате хорошо юнит тесты иметь. Они тут прям направшиваются.
Можете попробовать catch2 или doctest или тест фрэймворк.

Через GitHub Actions можно автоматические провеки сделать.
Как кстате и автоматические проверки кодстиля через clang-format

2022-02-09 07:50 UTC, irina-scherbitskaya commented on modules/actors/vehicles/atSpg.cpp
> +    if (d == 1)
все эти характеристики хорошо бы занести в Vehicle, как минимум

2022-02-09 07:52 UTC, irina-scherbitskaya commented on modules/actors/vehicles/vehicle.h
> +    const int SPEED_POINTS;
очень странно выглядит, обычно так константы обозначают

2022-02-21 07:33 UTC, BrychDaneel approved these changes
GUI вцелом приятное, понравилось.
Работа с препятсвиями появилась, отлично.
Отдельный лайк за кросплатформенность с сокетами на SFML.

Что еще нужно доработать так это работу с потоками: задумка целом хороша и разбиение грамотное, но синхронизации нет никакой (ну кроме слипов, что прям такое себе). Ну и код по памяти продолжает течь.

2022-02-21 07:33 UTC, BrychDaneel commented on README.md
> +<!-- Help me please. What a long line!!! -->
??

2022-02-21 07:33 UTC, BrychDaneel commented on modules/gui/shapes/VehicleLogo.cpp
> +    auto *detail = new sf::RectangleShape(sf::Vector2f(2 * r / std::sqrt(2.f), r * 0.15 * (separatorCount - 1)));
А код всё течет и течет...

2022-03-15 21:58 UTC, merged